<template>
  <div>
    <table border="1" cellspacing="0" cellpadding="3">
      <thead>
        <tr>
          <th colspan="8">规划纵三路道路施工进度统计</th>
          <th colspan="37">统计日期：2024年8月17日</th>
        </tr>

        <tr>
          <th rowspan="2">任务内容</th>
          <th rowspan="2">分部工程</th>
          <th colspan="2">计划</th>
          <th colspan="2">实际</th>
          <!-- <th rowspan="2">进度状态</th> -->
          <th rowspan="2">完成比例</th>
          <th rowspan="4">施工进度偏差情况</th>
          <th colspan="6" v-for="(date, index) in progressDates" :key="'header-' + index">
            {{ date }}
          </th>
        </tr>
        <tr>
          <th>开始</th>
          <th>结束</th>
          <th>开始</th>
          <th>结束</th>
          <th v-for="(day, index) in progressDays" :key="'day-' + index">{{ day }}</th>
        </tr>
        <tr></tr>
      </thead>

      <tbody>
        <tr v-for="(row, rowIndex) in tableData" :key="'row-' + rowIndex">
          <td v-if="rowIndex === 0" rowspan="4">{{ row.category0 }}</td>
          <td v-if="rowIndex > 3">{{ row.category0 }}</td>

          <td>{{ row.category }}</td>
          <td>{{ row.plannedStart }}</td>
          <td>{{ row.plannedEnd }}</td>
          <td>{{ row.actualStart }}</td>
          <td>{{ row.actualEnd }}</td>
          <!-- <td>{{ row.status }}</td> -->
          <td>{{ row.completionRate }}</td>
          <td>{{ row.remarks }}</td>
          <td
            v-for="(cell, cellIndex) in row.progress"
            :key="'cell-' + cellIndex"
            :style="{
              backgroundColor:
                cell === 'blue' ? 'blue' : cell === 'red' ? 'red' : cell === 'green' ? 'green' : 'transparent',
            }"
          ></td>
        </tr>
      </tbody>
    </table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      progressDates: ["8/1/2024", "9/1/2024", "10/1/2024", "11/1/2024", "12/1/2024", "1/1/2025"],
      progressDays: [
        "05",
        "10",
        "15",
        "20",
        "25",
        "30",
        "05",
        "10",
        "15",
        "20",
        "25",
        "30",
        "05",
        "10",
        "15",
        "20",
        "25",
        "30",
        "05",
        "10",
        "15",
        "20",
        "25",
        "30",
        "05",
        "10",
        "15",
        "20",
        "25",
        "30",
        "05",
        "10",
        "15",
        "20",
        "25",
        "30",
      ],
      tableData: [
        {
          category0: "道路工程",
          category: "道路路基",
          plannedStart: "2024.8.1",
          plannedEnd: "2024.9.21",
          actualStart: "2024.8.1",
          actualEnd: "正在施工",
          // status: "/",
          completionRate: "10%",
          remarks: "正常",
          progress: [
            "green",
            "green",
            "green",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
        {
          category0: "道路工程",
          category: "道路基层",
          plannedStart: "2024.9.21",
          plannedEnd: "2024.10.20",
          actualStart: "/",
          actualEnd: "/",
          // status: "/",
          completionRate: "/",
          remarks: "/",
          progress: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
        {
          category0: "道路工程",
          category: "道路路面",
          plannedStart: "2024.10.21",
          plannedEnd: "2024.12.10",
          actualStart: "/",
          actualEnd: "/",
          // status: "/",
          completionRate: "/",
          remarks: "/",
          progress: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
        {
          category0: "道路工程",
          category: "人行道",
          plannedStart: "2024.10.31",
          plannedEnd: "2024.12.10",
          actualStart: "/",
          actualEnd: "/",
          // status: "/",
          completionRate: "/",
          remarks: "/",
          progress: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
        {
          category0: "桥梁工程",
          category: "/",
          plannedStart: "2024.8.1",
          plannedEnd: "2024.12.5",
          actualStart: "2024.8.2",
          actualEnd: "正在施工",
          // status: "正在施工",
          completionRate: "8%",
          remarks: "滞后一天开始",
          progress: [
            "red",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
        {
          category0: "给排水管道工程",

          category: "/",
          plannedStart: "2024.8.26",
          plannedEnd: "2024.11.25",
          actualStart: "/",
          actualEnd: "/",
          // status: "/",
          completionRate: "/",
          remarks: "/",
          progress: [
            "",
            "",
            "",
            "",
            "",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
        {
          category0: "电力管沟工程",
          category: "/",

          plannedStart: "2024.9.5",
          plannedEnd: "2024.11.30",
          actualStart: "/",
          actualEnd: "/",
          // status: "/",
          completionRate: "/",
          remarks: "/",
          progress: [
            "",
            "",
            "",
            "",
            "",
            "",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
        {
          category0: "交通工程",

          category: "/",
          plannedStart: "2024.11.15",
          plannedEnd: "2024.12.30",
          actualStart: "/",
          actualEnd: "/",
          // status: "/",
          completionRate: "/",
          remarks: "/",
          progress: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
        {
          category0: "照明工程",
          category: "/",

          plannedStart: "2024.12.6",
          plannedEnd: "2024.12.30",
          actualStart: "/",
          actualEnd: "/",
          // status: "/",
          completionRate: "/",
          remarks: "/",
          progress: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "blue",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
        {
          category0: "绿化工程",
          category: "/",

          plannedStart: "2024.12.11",
          plannedEnd: "2024.12.30",
          actualStart: "/",
          actualEnd: "/",
          // status: "/",
          completionRate: "/",
          remarks: "/",
          progress: [
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "",
            "blue",
            "blue",
            "blue",
            "blue",
            "",
            "",
            "",
            "",
            "",
            "",
          ],
        },
      ],
    };
  },
};
</script>

<style scoped>
table {
  width: 100%;
  border-collapse: collapse;
}

th,
td {
  text-align: center;
  padding: 7px;
}

th {
  background-color: #2c3e50;
  color: white;
}

td {
  color: white;
}

table {
  background-color: rgba(0, 0, 0, 0.7);
}
</style>
